run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - asasalint
    - durationcheck
    - exportloopref
    - gocheckcompilerdirectives
    - gosimple
    - gosmopolitan
    - govet
    - ineffassign
    - nilerr
    - reassign
    - staticcheck
    - typecheck
    - unused
    - exhaustive
    - gochecksumtype
issues:
  exclude-rules:
    - path: '(.+)\.ragel\.go'
      linters:
        - ineffassign
    - linters:
        - staticcheck
      text: "SA1019:"

    # TODO(nikolay-govorov): fix linters in toytlv
    - path: 'toytlv\/(.+)\.go'
      linters:
        - staticcheck
        - ineffassign
        - gosimple
